// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddiitcuhixhbazvklpgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkaWl0Y3VoaXhoYmF6dmtscGdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzM5OTUsImV4cCI6MjA2MzY0OTk5NX0.e1qTwUuvaObXCcVRUjr6_SGBqPBeEJiE5t5mALxbJGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);